name: Build release version

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*.*.*' # Se dispara con v1.0, v2.1.3, etc.
    paths: # Solo compila si alguno de estos paths es modificado
      - 'InventarioILS/**'
      - '**.cs'
      - '**.xaml'
      - '**.iss'           # Setup file

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
    - name: Fetch code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Get tag version
      shell: bash
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        echo "APP_VERSION=${TAG#v}" >> $GITHUB_ENV

    - name: Dotnet publish
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:InformationalVersion="${{ env.APP_VERSION }}" /p:IncludeSourceRevisionInInformationalVersion=false -o ./publish

    - name: Compile .ISS to .EXE Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: installer.iss
        options: /O+
      env:
        APP_VERSION: ${{ env.APP_VERSION }}
        CLEAN_APP_VERSION: ${{ env.APP_VERSION }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: ./installer_output/*.exe
        name: Release v${{ env.APP_VERSION }}
        body: "New stable version for InventarioILS. This version was autogenerated after v${{ env.APP_VERSION }} tag."
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
