name: Bump build version

on:
  push:
    branches: [ migrate ]

jobs:
  bump:
    runs-on: ubuntu-latest
    name: Build and bump version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Bump build version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: "src/InventarioILS.csproj"
          version: bump-build

      - run: |
          git config user.name "TiagoGonM"
          git config user.email "tiagogonzalez2024@gmail.com"
          git add .
          git commit -m "Bump project version to ${{ steps.bump.outputs.newVersion }}"
          git push
