name: Build and pack App

on:
  push:
    branches: [ main ] # Se dispara cuando subes a main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest # Importante: Inno Setup necesita Windows

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Ajusta a tu versi√≥n

    # 1. Compilar y publicar la app (preparar los archivos)
    - name: Publish App
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

    # 2. Ejecutar Inno Setup
    - name: Compile Installer
      uses: Calofut/Inno-Setup-Action@v1
      with:
        filepath: 'installer.iss' # El archivo que creamos arriba

    # 3. Subir el instalador resultante a GitHub para descargarlo
    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: GestorInventario-Setup
        path: installer_output/*.exe
